from turtle import *

screen = Screen()
screen.bgcolor("#4cbbd9")
turtle = Turtle()
turtle.shape("turtle")
turtle.speed(10)
turtle.pensize(3)
#Cây
turtle.penup()
turtle.goto(255,-150)
turtle.pendown()
turtle.setheading(265)
turtle.begin_fill()
turtle.fillcolor("#7a7a52")
turtle.fd(100)
turtle.setheading(0)
turtle.fd(60)
turtle.setheading(95)
turtle.fd(100)
turtle.setheading(180)
turtle.fd(40)
turtle.end_fill()
#Lá cây
y = 60
color = ["#00ff55","#00cc44","#009933"]
for i in range(0,len(color)):
    y = y-70
    turtle.penup()
    turtle.goto(200,y)
    turtle.pendown()
    turtle.setheading(0)
    turtle.begin_fill()
    turtle.fillcolor(color[i])
    turtle.fd(150)
    turtle.lt(138)
    turtle.fd(100)
    turtle.lt(83)
    turtle.fd(100)
    turtle.end_fill()
#Cây2
turtle.penup()
turtle.goto(-350,-150)
turtle.pendown()
turtle.setheading(265)
turtle.begin_fill()
turtle.fillcolor("#7a7a52")
turtle.fd(100)
turtle.setheading(0)
turtle.fd(60)
turtle.setheading(95)
turtle.fd(100)
turtle.setheading(180)
turtle.fd(40)
turtle.end_fill()
#Lá cây
y = 60
color = ["#00ff55","#00cc44","#009933"]
for i in range(0,len(color)):
    y = y-70
    turtle.penup()
    turtle.goto(-400,y)
    turtle.pendown()
    turtle.setheading(0)
    turtle.begin_fill()
    turtle.fillcolor(color[i])
    turtle.fd(150)
    turtle.lt(138)
    turtle.fd(100)
    turtle.lt(83)
    turtle.fd(100)
    turtle.end_fill()
#Nhà
turtle.penup()
turtle.goto(-200,0)
turtle.pendown()
turtle.color("blue")
turtle.setheading(0)
turtle.fd(300)
turtle.setheading(270)
turtle.fd(100)
turtle.setheading(180)
turtle.fd(120)
turtle.setheading(90)
for i in range(3):
    turtle.fd(60)
    turtle.lt(90)
turtle.setheading(180)
turtle.fd(120)
turtle.setheading(90)
turtle.fd(100)
turtle.rt(50)
turtle.fd(120)
turtle.rt(80)
turtle.fd(120)
turtle.penup()
turtle.goto(-60,40)
turtle.pendown()
turtle.setheading(90)
turtle.fd(30)
turtle.rt(90)
turtle.fd(20)
turtle.rt(90)
turtle.fd(50)
turtle.penup()
turtle.goto(-60,80)
turtle.pendown()
turtle.setheading(90)
turtle.fd(20)
turtle.penup()
turtle.goto(-40,80)
turtle.pendown()
turtle.setheading(90)
turtle.fd(40)

screen.exitonclick()