from turtle import Screen,Turtle
turtle = Turtle()
window = Screen()
turtle.pensize(5)
turtle.speed("fastest")
def hinhchunhat(x,y):
    turtle.penup()
    turtle.goto(x,y)
    turtle.pendown()
    turtle.setheading(0)
    turtle.begin_fill()
    turtle.fillcolor("pink")
    for i in range(2):
        turtle.fd(100)
        turtle.lt(90)
        turtle.fd(150)
        turtle.lt(90)
    turtle.end_fill()
def hinhchunhat2(x,y):
    turtle.penup()
    turtle.goto(x, y)
    turtle.pendown()
    turtle.setheading(0)
    turtle.begin_fill()
    turtle.fillcolor("white")
    for i in range(2):
        turtle.fd(35)
        turtle.lt(90)
        turtle.fd(50)
        turtle.lt(90)
    turtle.end_fill()
def hinhchunhat3(x,y):
    turtle.penup()
    turtle.goto(x, y)
    turtle.pendown()
    turtle.setheading(0)
    turtle.begin_fill()
    turtle.fillcolor("#00802b")
    for i in range(2):
        turtle.fd(30)
        turtle.lt(90)
        turtle.fd(70)
        turtle.lt(90)
    turtle.end_fill()
def hinhvuong(x,y):
    turtle.penup()
    turtle.goto(x, y)
    turtle.pendown()
    turtle.setheading(0)
    turtle.begin_fill()
    turtle.fillcolor("#adad85")
    for i in range(4):
        turtle.fd(150)
        turtle.lt(90)
    turtle.end_fill()
hinhchunhat(0,0)
hinhchunhat2(35,50)
hinhchunhat(100,0)
hinhchunhat2(135,50)
hinhchunhat(100,150)
hinhchunhat2(135,200)
hinhchunhat(0,150)
hinhchunhat2(35,200)
hinhvuong(200,0)
hinhchunhat3(250,0)
hinhchunhat3(280,0)
window.exitonclick()