from turtle import *

screen = Screen()
screen.bgcolor("#4cbbd9")
turtle = Turtle()
turtle.shape("turtle")
turtle.speed(10)
turtle.pensize(3)

#Vẽ ngôi nhà
#Nhà
turtle.penup()
turtle.goto(-370,-250)
turtle.setheading(90)
turtle.pendown()
turtle.begin_fill()
turtle.fillcolor("#007eff")
turtle.fd(200)
turtle.rt(90)
turtle.fd(210)
turtle.rt(90)
turtle.fd(200)
turtle.rt(90)
turtle.fd(210)
turtle.end_fill()
#Cánh cửa
turtle.penup()
turtle.goto(-300,-250)
turtle.pendown()
turtle.setheading(90)
turtle.fillcolor("#90ff9c")
turtle.begin_fill()
turtle.fd(100)
turtle.rt(90)
turtle.fd(70)
turtle.rt(90)
turtle.fd(100)
turtle.rt(90)
turtle.fd(70)
turtle.end_fill()
#Mái nhà
turtle.penup()
turtle.goto(-370,-50)
turtle.pendown()
turtle.begin_fill()
turtle.fillcolor("pink")
turtle.setheading(90)
turtle.rt(45)
turtle.fd(150)
turtle.rt(90)
turtle.fd(150)
turtle.end_fill()
#Mái nhà sau
turtle.setheading(20)
turtle.begin_fill()
turtle.fillcolor("orange")
turtle.fd(150)
turtle.lt(110)
turtle.fd(150)
turtle.lt(72)
turtle.fd(160)
turtle.end_fill()
#Mặt sau nhà
turtle.penup()
turtle.goto(-158,-250)
turtle.pendown()
turtle.begin_fill()
turtle.fillcolor("yellow")
turtle.setheading(20)
turtle.fd(150)
turtle.lt(70)
turtle.fd(200)
turtle.lt(110)
turtle.fd(150)
turtle.end_fill()
#Cửa sổ
turtle.penup()
turtle.goto(-110,-160)
turtle.pendown()
turtle.setheading(20)
turtle.begin_fill()
turtle.fillcolor("red")
turtle.fd(70)
turtle.lt(70)
turtle.fd(70)
turtle.lt(110)
turtle.fd(70)
turtle.lt(70)
turtle.fd(70)
turtle.end_fill()
#Cây
turtle.penup()
turtle.goto(150,-250)
turtle.pendown()
turtle.begin_fill()
turtle.fillcolor("red")
turtle.setheading(0)
turtle.fd(50)
turtle.lt(90)
turtle.fd(100)
turtle.lt(90)
turtle.fd(50)
turtle.lt(90)
turtle.fd(100)
turtle.end_fill()
#lá cây
y = 60
for i in range(3):
    y = y-70
    turtle.penup()
    turtle.goto(100,y)
    turtle.pendown()
    turtle.setheading(0)
    turtle.begin_fill()
    turtle.fillcolor("#90ff9c")
    turtle.fd(150)
    turtle.lt(138)
    turtle.fd(100)
    turtle.lt(83)
    turtle.fd(100)
    turtle.end_fill()
#Mặt trời
turtle.penup()
turtle.goto(200,300)
turtle.pendown()
turtle.begin_fill()
turtle.fillcolor("yellow")
turtle.circle(70)
turtle.end_fill()
turtle.penup()

screen.exitonclick()